# this notebook is for numpy basic liabrary 

In [1]:
import numpy as np

In [2]:
lst=[1,2,3,4]
arr=np.array(lst)  #makeing array from list is it called nd array means n dimensional array

In [5]:
arr
type(arr)

numpy.ndarray

In [6]:
arr.shape

(4,)

In [7]:
lst2=[2,3,4,5]
lst3=[3,4,5,6]

In [8]:
arr2=np.array([lst,lst2,lst3])

In [9]:
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [10]:
arr2.shape

(3, 4)

In [13]:
arr2[:,1]   #[x:y:z,a:b:c]====>x start of row y end of limit of row slicing and z is step and a,b,c are also start,end and step.

array([2, 3, 4])

In [14]:
arr2[1:,1:3]

array([[3, 4],
       [4, 5]])

In [15]:
arr2[1:,3:]

array([[5],
       [6]])

In [19]:
arr2.reshape(12,1)

array([[1],
       [2],
       [3],
       [4],
       [2],
       [3],
       [4],
       [5],
       [3],
       [4],
       [5],
       [6]])

In [20]:
arr2.reshape(2,6)

array([[1, 2, 3, 4, 2, 3],
       [4, 5, 3, 4, 5, 6]])

In [21]:
np.arange(1,10,2) # 1 is start 10 is end and 2 is step

array([1, 3, 5, 7, 9])

In [22]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.random.randint(10,50,4)  #return nd array of size 4 range between 10 to 40

array([49, 38, 30, 14])

In [26]:
np.random.random_sample((2,2))   #2,2 is size of this

array([[0.11137571, 0.90972047],
       [0.4965932 , 0.65523581]])